### ISSUE TITLE
Highlight the line and column of the selected cell

### ISSUE THREAD

**Issue by ElisaRegnier** [joffreyBerrier/vuejs-spreadsheet#166]
I'd like to highlight horizontally and vertically the line number and the column title of the selected cell

**Comment by MatthiasRMS** [comment]
Me too, I've been waiting for this feature for years !! 👍 🎖

**Comment by joffreyBerrier** [comment]
Hi @ElisaRegnier thx for this great improvement ! I have merge your code on master and update the component on npm

have fun ⭐️ 

Thx

**Comment by MatthiasRMS** [comment]
WAHOU AMAZING THX A LOT @ElisaRegnier 👏 😱
